export const categories = [
  { id: 1, name: 'フロントエンド' },
  { id: 2, name: 'バックエンド' },
  { id: 3, name: 'インフラ' },
  { id: 4, name: 'JavaScript' },
  { id: 5, name: 'TypeScript' },
  { id: 6, name: 'PHP' },
  { id: 7, name: 'Python' },
  { id: 8, name: 'Ruby' },
  { id: 9, name: 'Go' },
  { id: 10, name: 'Node.js' },
  { id: 11, name: 'Java' },
  { id: 12, name: 'Vue.js' },
  { id: 13, name: 'React' },
  { id: 14, name: 'Next.js' },
  { id: 15, name: 'Nuxt.js' },
  { id: 16, name: 'NestJS' },
  { id: 17, name: 'Laravel' },
  { id: 18, name: 'AWS' },
  { id: 19, name: 'GCP' },
  { id: 20, name: 'Docker' },
  { id: 21, name: 'GitHub' },
  { id: 22, name: 'Firebase' },
  { id: 23, name: 'Supabase' },
  { id: 24, name: 'CSS' },
  { id: 25, name: 'Tailwind CSS' },
  { id: 26, name: 'Flutter' },
  { id: 27, name: 'React Native' },
  { id: 28, name: 'Rails' },
  { id: 29, name: 'iOS' },
  { id: 30, name: 'Android' },
];
